# Generated by Django 4.1.3 on 2022-11-30 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technicien', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Managere',
            new_name='Menagere',
        ),
    ]
