# Generated by Django 4.1.3 on 2022-12-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicien', '0002_rename_managere_menagere'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriculture',
            name='categorie',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='categorie',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='coiffure',
            name='categorie',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='comptable',
            name='categorie',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='cuisinier',
            name='categorie',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='developpeur',
            name='categorie',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='electricien',
            name='categorie',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='elevage',
            name='categorie',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='categorie',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='fille_et_garçon_salle',
            name='categorie',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='gardien',
            name='categorie',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='gardinier',
            name='categorie',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='genie_civil',
            name='categorie',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='gestionnaire',
            name='categorie',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='infographe',
            name='categorie',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='informaticien',
            name='categorie',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='installation_antenne',
            name='categorie',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='logisticien',
            name='categorie',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='maintenancier',
            name='categorie',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='manager',
            name='categorie',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='marketeur',
            name='categorie',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='maçon',
            name='categorie',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='mecanicien',
            name='categorie',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='menagere',
            name='categorie',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='categorie',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='peintre',
            name='categorie',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='plombier',
            name='categorie',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='reparateur_phone',
            name='categorie',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='reparateur_tele',
            name='categorie',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='tolerie',
            name='categorie',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='veterinaire',
            name='categorie',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
