# Generated by Django 4.1.3 on 2022-12-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicien', '0003_agriculture_categorie_chauffeur_categorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticien',
            name='categorie',
            field=models.CharField(blank=True, default='logisticien', max_length=150),
        ),
    ]
