# Generated by Django 4.1.3 on 2022-12-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicien', '0004_alter_logisticien_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agriculture',
            name='categorie',
            field=models.CharField(blank=True, default='agriculture', max_length=150),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='categorie',
            field=models.CharField(blank=True, default='chauffeur', max_length=150),
        ),
        migrations.AlterField(
            model_name='coiffure',
            name='categorie',
            field=models.CharField(blank=True, default='coiffure', max_length=150),
        ),
        migrations.AlterField(
            model_name='comptable',
            name='categorie',
            field=models.CharField(blank=True, default='comptable', max_length=150),
        ),
        migrations.AlterField(
            model_name='cuisinier',
            name='categorie',
            field=models.CharField(blank=True, default='cuisinier', max_length=150),
        ),
        migrations.AlterField(
            model_name='developpeur',
            name='categorie',
            field=models.CharField(blank=True, default='developpeur', max_length=150),
        ),
        migrations.AlterField(
            model_name='electricien',
            name='categorie',
            field=models.CharField(blank=True, default='electricien', max_length=150),
        ),
        migrations.AlterField(
            model_name='elevage',
            name='categorie',
            field=models.CharField(blank=True, default='elevage', max_length=150),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='categorie',
            field=models.CharField(blank=True, default='enseignant', max_length=150),
        ),
        migrations.AlterField(
            model_name='fille_et_garçon_salle',
            name='categorie',
            field=models.CharField(blank=True, default='servante', max_length=150),
        ),
        migrations.AlterField(
            model_name='gardien',
            name='categorie',
            field=models.CharField(blank=True, default='gardien', max_length=150),
        ),
        migrations.AlterField(
            model_name='gardinier',
            name='categorie',
            field=models.CharField(blank=True, default='gardinier', max_length=150),
        ),
        migrations.AlterField(
            model_name='genie_civil',
            name='categorie',
            field=models.CharField(blank=True, default='genie_civil', max_length=150),
        ),
        migrations.AlterField(
            model_name='gestionnaire',
            name='categorie',
            field=models.CharField(blank=True, default='gestionnaire', max_length=150),
        ),
        migrations.AlterField(
            model_name='infographe',
            name='categorie',
            field=models.CharField(blank=True, default='infographie', max_length=150),
        ),
        migrations.AlterField(
            model_name='informaticien',
            name='categorie',
            field=models.CharField(blank=True, default='informaticien', max_length=150),
        ),
        migrations.AlterField(
            model_name='installation_antenne',
            name='categorie',
            field=models.CharField(blank=True, default='installation_antenne', max_length=150),
        ),
        migrations.AlterField(
            model_name='maintenancier',
            name='categorie',
            field=models.CharField(blank=True, default='maintenancier', max_length=150),
        ),
        migrations.AlterField(
            model_name='manager',
            name='categorie',
            field=models.CharField(blank=True, default='manager', max_length=150),
        ),
        migrations.AlterField(
            model_name='marketeur',
            name='categorie',
            field=models.CharField(blank=True, default='marketeur', max_length=150),
        ),
        migrations.AlterField(
            model_name='maçon',
            name='categorie',
            field=models.CharField(blank=True, default='maçon', max_length=150),
        ),
        migrations.AlterField(
            model_name='mecanicien',
            name='categorie',
            field=models.CharField(blank=True, default='mecanicien', max_length=150),
        ),
        migrations.AlterField(
            model_name='menagere',
            name='categorie',
            field=models.CharField(blank=True, default='menagere', max_length=150),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='categorie',
            field=models.CharField(blank=True, default='multimedia', max_length=150),
        ),
        migrations.AlterField(
            model_name='peintre',
            name='categorie',
            field=models.CharField(blank=True, default='peintre', max_length=150),
        ),
        migrations.AlterField(
            model_name='plombier',
            name='categorie',
            field=models.CharField(blank=True, default='plombier', max_length=150),
        ),
        migrations.AlterField(
            model_name='reparateur_phone',
            name='categorie',
            field=models.CharField(blank=True, default='reparateur_phone', max_length=150),
        ),
        migrations.AlterField(
            model_name='reparateur_tele',
            name='categorie',
            field=models.CharField(blank=True, default='reparateur_appareil_electronique', max_length=150),
        ),
        migrations.AlterField(
            model_name='tolerie',
            name='categorie',
            field=models.CharField(blank=True, default='tolerie', max_length=150),
        ),
        migrations.AlterField(
            model_name='veterinaire',
            name='categorie',
            field=models.CharField(blank=True, default='veterinaire', max_length=150),
        ),
    ]
