# Generated by Django 4.1.3 on 2022-12-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicien', '0006_alter_coiffure_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coiffure',
            name='categorie',
            field=models.CharField(blank=True, default='coiffure', max_length=150),
        ),
    ]
