# Generated by Django 4.1.3 on 2022-12-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicien', '0007_alter_coiffure_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developpeur',
            name='categorie',
            field=models.CharField(blank=True, default='développeur', max_length=150),
        ),
        migrations.AlterField(
            model_name='genie_civil',
            name='categorie',
            field=models.CharField(blank=True, default='génie_civil', max_length=150),
        ),
        migrations.AlterField(
            model_name='marketeur',
            name='categorie',
            field=models.CharField(blank=True, default='markéteur', max_length=150),
        ),
        migrations.AlterField(
            model_name='mecanicien',
            name='categorie',
            field=models.CharField(blank=True, default='mécanicien', max_length=150),
        ),
        migrations.AlterField(
            model_name='menagere',
            name='categorie',
            field=models.CharField(blank=True, default='ménagère', max_length=150),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='categorie',
            field=models.CharField(blank=True, default='multimédia', max_length=150),
        ),
        migrations.AlterField(
            model_name='reparateur_phone',
            name='categorie',
            field=models.CharField(blank=True, default='réparateur_phone', max_length=150),
        ),
        migrations.AlterField(
            model_name='reparateur_tele',
            name='categorie',
            field=models.CharField(blank=True, default='réparateur_appareil_electronique', max_length=150),
        ),
        migrations.AlterField(
            model_name='tolerie',
            name='categorie',
            field=models.CharField(blank=True, default='tolérie', max_length=150),
        ),
        migrations.AlterField(
            model_name='veterinaire',
            name='categorie',
            field=models.CharField(blank=True, default='vétérinaire', max_length=150),
        ),
    ]
