# Generated by Django 4.1.3 on 2022-11-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_imagepricipale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='entête')),
                ('titre1', models.CharField(max_length=255)),
                ('titre2', models.CharField(max_length=255)),
            ],
        ),
    ]
