# Generated by Django 4.1.3 on 2022-11-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_entete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dernierpublication',
            name='description',
            field=models.TextField(),
        ),
    ]
