# Generated by Django 4.1.3 on 2022-12-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_entete_titre1_alter_entete_titre2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menbre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('domaine', models.CharField(max_length=250)),
                ('photo', models.ImageField(upload_to='menbres')),
                ('facebook', models.CharField(max_length=350)),
                ('whatsapp', models.CharField(max_length=350)),
                ('phone', models.CharField(max_length=200)),
            ],
        ),
    ]
