# Generated by Django 4.1.3 on 2022-12-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_menbre'),
    ]

    operations = [
        migrations.AddField(
            model_name='menbre',
            name='fonction',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
