# Generated by Django 4.1.3 on 2022-12-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_menbre_fonction'),
    ]

    operations = [
        migrations.AddField(
            model_name='dernierpublication',
            name='par',
            field=models.CharField(default='Admin', max_length=150),
        ),
    ]
